version: '3'

services:
  web:
    build: .
    ports:
    - "8000:8000"

    volume:
      - .:/app

    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword 

    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data
      